// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.5
// source: types/common.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HttpStatus int32

const (
	HttpStatus_Ok         HttpStatus = 0
	HttpStatus_Forbiden   HttpStatus = 1
	HttpStatus_BadRequest HttpStatus = 2
	HttpStatus_Existed    HttpStatus = 3
	HttpStatus_Invalid    HttpStatus = 4
	HttpStatus_NotFound   HttpStatus = 5
	HttpStatus_Error      HttpStatus = 6
)

// Enum value maps for HttpStatus.
var (
	HttpStatus_name = map[int32]string{
		0: "Ok",
		1: "Forbiden",
		2: "BadRequest",
		3: "Existed",
		4: "Invalid",
		5: "NotFound",
		6: "Error",
	}
	HttpStatus_value = map[string]int32{
		"Ok":         0,
		"Forbiden":   1,
		"BadRequest": 2,
		"Existed":    3,
		"Invalid":    4,
		"NotFound":   5,
		"Error":      6,
	}
)

func (x HttpStatus) Enum() *HttpStatus {
	p := new(HttpStatus)
	*p = x
	return p
}

func (x HttpStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HttpStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_types_common_proto_enumTypes[0].Descriptor()
}

func (HttpStatus) Type() protoreflect.EnumType {
	return &file_types_common_proto_enumTypes[0]
}

func (x HttpStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HttpStatus.Descriptor instead.
func (HttpStatus) EnumDescriptor() ([]byte, []int) {
	return file_types_common_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_types_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_types_common_proto_rawDescGZIP(), []int{0}
}

var File_types_common_proto protoreflect.FileDescriptor

var file_types_common_proto_rawDesc = []byte{
	0x0a, 0x12, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x22, 0x07, 0x0a, 0x05, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x2a, 0x65, 0x0a, 0x0a, 0x48, 0x74, 0x74, 0x70, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x6b, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x6f,
	0x72, 0x62, 0x69, 0x64, 0x65, 0x6e, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x42, 0x61, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x78, 0x69, 0x73,
	0x74, 0x65, 0x64, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x10, 0x05,
	0x12, 0x09, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x06, 0x42, 0x25, 0x5a, 0x23, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x65, 0x72, 0x66, 0x65, 0x63,
	0x74, 0x62, 0x75, 0x69, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x2f, 0x70, 0x62, 0x2f, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_types_common_proto_rawDescOnce sync.Once
	file_types_common_proto_rawDescData = file_types_common_proto_rawDesc
)

func file_types_common_proto_rawDescGZIP() []byte {
	file_types_common_proto_rawDescOnce.Do(func() {
		file_types_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_types_common_proto_rawDescData)
	})
	return file_types_common_proto_rawDescData
}

var file_types_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_types_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_types_common_proto_goTypes = []interface{}{
	(HttpStatus)(0), // 0: types.HttpStatus
	(*Empty)(nil),   // 1: types.Empty
}
var file_types_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_types_common_proto_init() }
func file_types_common_proto_init() {
	if File_types_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_types_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_types_common_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_common_proto_goTypes,
		DependencyIndexes: file_types_common_proto_depIdxs,
		EnumInfos:         file_types_common_proto_enumTypes,
		MessageInfos:      file_types_common_proto_msgTypes,
	}.Build()
	File_types_common_proto = out.File
	file_types_common_proto_rawDesc = nil
	file_types_common_proto_goTypes = nil
	file_types_common_proto_depIdxs = nil
}
